"""security hardening: otp hashing, attempt limiting, token invalidation, indexes

Revision ID: c4ffdcdd413c
Revises: 844a86b079e6
Create Date: 2026-10-07 12:13:49.393527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4ffdcdd413c'
down_revision: Union[str, None] = '844a86b079e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_tokens', sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('password_reset_tokens', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=sa.false(),
               nullable=False)
    op.drop_index('ix_password_reset_tokens_token', table_name='password_reset_tokens')
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index('ix_password_reset_user_active', 'password_reset_tokens', ['user_id', 'is_used'], unique=False)
    op.drop_constraint('password_reset_tokens_user_id_fkey', 'password_reset_tokens', type_='foreignkey')
    # Named explicitly so downgrade() can drop it; autogenerate emits None here,
    # which makes the reverse migration fail.
    op.create_foreign_key(
        'password_reset_tokens_user_id_fkey', 'password_reset_tokens', 'users',
        ['user_id'], ['id'], ondelete='CASCADE'
    )
    # The token column now stores an HMAC-SHA256 digest rather than the OTP.
    op.alter_column('password_reset_tokens', 'token',
               existing_type=sa.VARCHAR(),
               type_=sa.String(length=64),
               existing_nullable=False)
    # Any rows predating this change hold plaintext OTPs that can no longer be
    # verified. They are short-lived by design, so discard them rather than
    # leaving unusable tokens behind.
    op.execute('DELETE FROM password_reset_tokens')
    op.create_index('ix_todos_owner_created', 'todos', ['owner_id', sa.text('created_at DESC')], unique=False)
    op.add_column('users', sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.true(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_column('users', 'password_changed_at')
    op.drop_index('ix_todos_owner_created', table_name='todos')
    op.alter_column('password_reset_tokens', 'token',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint('password_reset_tokens_user_id_fkey', 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key('password_reset_tokens_user_id_fkey', 'password_reset_tokens', 'users', ['user_id'], ['id'])
    op.drop_index('ix_password_reset_user_active', table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.create_index('ix_password_reset_tokens_token', 'password_reset_tokens', ['token'], unique=True)
    op.alter_column('password_reset_tokens', 'is_used',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_column('password_reset_tokens', 'attempt_count')
    # ### end Alembic commands ###
